batch_size: 512 
n_epochs: 30
decay_epochs: [20,25]
momentum: 0.9
init_lr: 1e-3
weight_decay: 1e-4  # weight decaying rate
lr_decay: 0.1  # decaying rate for learning rate
n_epochs_to_log: 20
transforms: #data augmentation 
  base:
    resize: 
      size: [224,224] #[144,288]
    center_crop: 
      size: [224,224] #[128,256] #224
    to_tensor:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

samplers:
  train_val/train:
    BalancedBatchSampler:
      n_num: 3
      n_class: 50
loss_fn: 
  OnlineTripletLoss:
    selector: "hardest"
    margin: 1.0
task: vehicle_reid