batch_size: 256
n_epochs: 20
decay_epochs: [5,10,25]
momentum: 0.9
init_lr: 1e-4
weight_decay: 1e-4  # weight decaying rate
lr_decay: 0.1  # decaying rate for learning rate
n_epochs_to_log: 5
transforms: #data augmentation 
  base:
    resize: 
      size: 400 #[144,288]
    # center_crop: 
      size: 320 #[128,256] #224
    to_tensor:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  train_val/train:
    resize: 
      size: 400 #[144,288]
    horizon_flip:
    random_crop: 
      size: 320 #224
    to_tensor:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    random_erasing:

samplers:
  train_val/train:
    InstanceIdSampler:
      n_num: 5
      n_class: 15
loss_fn: 
  AIC20Loss:
    margin: 0.3
    num_classes: 230
    epsilon: 0.1
task: vehicle_reid