batch_size: 512 
n_epochs: 50
decay_epochs: [30,40]
momentum: 0.9
init_lr: 1e-3
weight_decay: 1e-4  # weight decaying rate
lr_decay: 0.1  # decaying rate for learning rate
n_epochs_to_log: 20
transforms: #data augmentation 
  base:
    resize: 
      size: [280,280] #[144,288]
    # center_crop: 
    #   size: [320,320] #[128,256] #224
    to_tensor:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  train_val/train:
    resize: 
      size: [280,280] #360 #[144,288]
    # vertical_flip:
    #   p: 0.05
    # center_crop: 
    #   size: [330,330] #320
    to_tensor:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    # random_erasing:

samplers:
  train_val/train:
    BalancedBatchSampler:
      n_num: 3
      n_class: 50
loss_fn: 
  OnlineTripletLoss:
    selector: "hardest"
    margin: 1.0
task: vehicle_reid