batch_size: 64
n_epochs: 10
decay_epochs: [5]
momentum: 0.9
init_lr: 1e-3
weight_decay: 1e-4  # weight decaying rate
lr_decay: 0.1  # decaying rate for learning rate
n_epochs_to_log: 1
data_augment: #data augmentation 
  resize: 
    size: 256
  center_crop: 
    size: 224
  to_tensor:
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
loss_fn: CrossEntropy
task: image_classification