dataset_name: 'AIC20_VEHI_REID'
dataset_params:
    data_root: '../aic20_data/origin/'
    spldata_dir: 
        train_val:
            train:      'image_train'
            gallery:    'image_train'
            query:      'image_train'
            h_gallery:  'image_train'
            h_query:    'image_train'
        test:
            gallery:  'image_test'
            query:    'image_query'
    lbl_fname: '../aic20_data/origin/train_label.xml'
    datalst_pth:
        train_val:
            train:      './dataset_splits/aic20_vehicle_reid/train_train.lst'
            gallery:    './dataset_splits/aic20_vehicle_reid/gallery_easy.lst'
            query:      './dataset_splits/aic20_vehicle_reid/query_easy.lst'
            h_gallery:  './dataset_splits/aic20_vehicle_reid/gallery_hard.lst'
            h_query:    './dataset_splits/aic20_vehicle_reid/query_hard.lst'
        test:
            gallery:    './dataset_splits/aic20_vehicle_reid/test.lst'
            query:      './dataset_splits/aic20_vehicle_reid/query.lst'